---
- hosts: all
  tasks:
    - name: Creating Folder
      file:
        path: /home/{{ ansible_user }}/{{ item }}
        state: directory
      loop: 
        - folder01
        - folder02
        - folder03

    - name: Creating Files
      file:
        path: /home/{{ ansible_user }}/{{ item.dir }}/{{ item.file }}
        state: touch
      loop:
        - { dir: "folder01", file: "file01" }
        - { dir: "folder02", file: "file02" }
        - { dir: "folder03", file: "file03" }