---
- name: Installing Apache Web Server
  hosts: all
  become: true
  tasks:
    - name: Setup Apache - Debian
      apt:
        update_cache: yes
        name: apache2
        state: present
      when: ansible_distribution == "Debian"

    - name: Start Apache - Debian
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Debian"

    - name: Setup Apache - RedHat
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "RedHat"

    - name: Start Apache - RedHat
      service:
        name: httpd
        state: started
      when: ansible_distribution == "RedHat"