- name: Example Playbook
  hosts: localhost
  vars:
    http_port: 80
    https_port: 443
  
    packages:
      - git
      - mysql-client
      - curl
      - wget
    
    appserver:
      hostsname: webapp01
      ipaddress: 192.168.1.10
      os: Windows Server 2019
  
  tasks:
    - name: Display the single vaariables
      debug:
        var: http_port, https_port
    
    - name: Display the list of variables
      debug:
        var: packages
    
    - name: Display the Dictionary of variables
      debug:
        var: appserver