---
# tasks file for roles/webserver

- name: Installing Apache
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Starting Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Copy Files
  ansible.builtin.copy: src=devops.png dest=/var/www/html/

- name: Generating Template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Restarting Apache